fix: update action versions in docker-publish.yml for consistency and compatibility

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -42,8 +42,8 @@ jobs:
       contents: read
       security-events: write
     steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
+      - uses: actions/checkout@v5
+      - uses: actions/setup-python@v6
         with:
           python-version: 3.11
       - uses: github/codeql-action/init@v4
@@ -69,13 +69,13 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+        uses: docker/setup-buildx-action@v4
 
       - name: Log into registry ${{ env.REGISTRY }}
-        uses: docker/login-action@v3
+        uses: docker/login-action@v4
         with:
           registry: ${{ env.REGISTRY }}
           username: groenator
@@ -95,26 +95,28 @@ jobs:
 
       - name: Extract Docker metadata
         id: meta
-        uses: docker/metadata-action@v5
+        uses: docker/metadata-action@v6
         with:
           flavor: |
             latest=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
           images: |
             ghcr.io/groenator/iptvboss-docker
           tags: |
+            type=ref,event=branch
             type=ref,event=pr
+            type=ref,event=tag
             type=semver,pattern=v{{major}}.{{minor}}
             type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
             type=semver,pattern=v{{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
             type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
-            type=raw,value=${{ env.LATEST_TAG }},enable=${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
+            type=raw,value=${{ env.LATEST_TAG }},enable=${{ github.event_name == 'release' || startsWith(github.ref, 'refs/tags/') }}
 
       - name: Short commit
         id: shortcommit
         run: echo "{name}={value}::$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
 
       - name: Build and push final image
-        uses: docker/build-push-action@v5
+        uses: docker/build-push-action@v6
         with:
           platforms: linux/amd64,linux/arm64
           labels: ${{ steps.meta.outputs.labels }}
@@ -125,78 +127,80 @@ jobs:
           context: .
           cache-from: type=gha
           cache-to: type=gha,mode=max
+
       - name: Clean Buildx Cache
         run: docker buildx prune -f --all
 
   build-headless-stable:
-      if: |
-        github.event_name == 'push' ||
-        github.event_name == 'release' ||
-        (
-          github.event_name == 'pull_request' &&
-          github.actor != 'dependabot[bot]'
-        )
-      needs: [codeql]
-      runs-on: ubuntu-latest
-      permissions:
-        contents: read
-        packages: write
-        id-token: write
-      steps:
-        - name: Checkout repository
-          uses: actions/checkout@v4
-        - name: Set up Docker Buildx
-          uses: docker/setup-buildx-action@v3
-        - name: Log into registry ${{ env.REGISTRY }}
-          uses: docker/login-action@v3
-          with:
-            registry: ${{ env.REGISTRY }}
-            username: groenator
-            password: ${{ secrets.GITHUB_TOKEN }}
+    if: |
+      github.event_name == 'push' ||
+      github.event_name == 'release' ||
+      (
+        github.event_name == 'pull_request' &&
+        github.actor != 'dependabot[bot]'
+      )
+    needs: [codeql]
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      packages: write
+      id-token: write
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v4
+      - name: Log into registry ${{ env.REGISTRY }}
+        uses: docker/login-action@v4
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: groenator
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-        - name: Check for release file
-          run: |
-            if [[ ! -f release || ! -s release ]]; then
-              echo "release file is missing or empty"
-              exit 1
-            fi
+      - name: Check for release file
+        run: |
+          if [[ ! -f release || ! -s release ]]; then
+            echo "release file is missing or empty"
+            exit 1
+          fi
 
-        - name: Set release tag as environment variable
-          id: set-stable-tag
-          run: |
-            echo -e "LATEST_TAG=$(cat release)" >> $GITHUB_ENV
-        - name: Extract Docker metadata
-          id: meta
-          uses: docker/metadata-action@v5
-          with:
-            flavor: |
-              latest=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
-            images: |
-              ghcr.io/groenator/iptvboss-docker-headless-stable
-            tags: |
-              type=ref,event=pr
-              type=semver,pattern=v{{major}}.{{minor}}
-              type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
-              type=semver,pattern=v{{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
-              type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
-              type=raw,value=${{ env.LATEST_TAG }},enable=${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
-        # Build and push Beta Image
-        - name: Short commit
-          id: shortcommit
-          run: echo "{name}={value}::$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
-        - name: Build and push final image
-          uses: docker/build-push-action@v5
-          with:
-            platforms: linux/amd64,linux/arm64
-            labels: ${{ steps.meta.outputs.labels }}
-            build-args: |
-              LATEST_TAG=${{ env.LATEST_TAG }}
-            tags: ${{ steps.meta.outputs.tags }}
-            push: true
-            context: .
-            file: Dockerfile.headless
-        - name: Clean Buildx Cache
-          run: docker buildx prune -f --all
+      - name: Set release tag as environment variable
+        id: set-stable-tag
+        run: |
+          echo -e "LATEST_TAG=$(cat release)" >> $GITHUB_ENV
+      - name: Extract Docker metadata
+        id: meta
+        uses: docker/metadata-action@v6
+        with:
+          flavor: |
+            latest=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
+          images: |
+            ghcr.io/groenator/iptvboss-docker-headless-stable
+          tags: |
+            type=ref,event=branch
+            type=ref,event=pr
+            type=ref,event=tag
+            type=semver,pattern=v{{major}}.{{minor}}
+            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
+            type=semver,pattern=v{{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
+            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
+            type=raw,value=${{ env.LATEST_TAG }},enable=${{ github.event_name == 'release' || startsWith(github.ref, 'refs/tags/') }}
+      - name: Short commit
+        id: shortcommit
+        run: echo "{name}={value}::$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+      - name: Build and push final image
+        uses: docker/build-push-action@v6
+        with:
+          platforms: linux/amd64,linux/arm64
+          labels: ${{ steps.meta.outputs.labels }}
+          build-args: |
+            LATEST_TAG=${{ env.LATEST_TAG }}
+          tags: ${{ steps.meta.outputs.tags }}
+          push: true
+          context: .
+          file: Dockerfile.headless
+      - name: Clean Buildx Cache
+        run: docker buildx prune -f --all
 
   build-beta:
     if: |
@@ -215,13 +219,13 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+        uses: docker/setup-buildx-action@v4
 
       - name: Log into registry ${{ env.REGISTRY }}
-        uses: docker/login-action@v3
+        uses: docker/login-action@v4
         with:
           registry: ${{ env.REGISTRY }}
           username: groenator
@@ -241,26 +245,28 @@ jobs:
 
       - name: Extract Docker metadata
         id: meta-beta
-        uses: docker/metadata-action@v5
+        uses: docker/metadata-action@v6
         with:
           flavor: |
             latest=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
           images: |
             ghcr.io/groenator/iptvboss-docker-beta
           tags: |
+            type=ref,event=branch
             type=ref,event=pr
+            type=ref,event=tag
             type=semver,pattern=v{{major}}.{{minor}}
             type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
             type=semver,pattern=v{{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
             type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
-            type=raw,value=${{ env.BETA_TAG }},enable=${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
+            type=raw,value=${{ env.BETA_TAG }},enable=${{ github.event_name == 'release' || startsWith(github.ref, 'refs/tags/') }}
 
       - name: Set short commit
         id: commit
         run: echo "{name}={value}::$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
 
       - name: Build and push final image
-        uses: docker/build-push-action@v5
+        uses: docker/build-push-action@v6
         with:
           platforms: linux/amd64,linux/arm64
           labels: ${{ steps.meta-beta.outputs.labels }}
@@ -289,13 +295,13 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+        uses: docker/setup-buildx-action@v4
 
       - name: Log into registry ${{ env.REGISTRY }}
-        uses: docker/login-action@v3
+        uses: docker/login-action@v4
         with:
           registry: ${{ env.REGISTRY }}
           username: groenator
@@ -315,19 +321,21 @@ jobs:
 
       - name: Extract Docker metadata
         id: meta-beta
-        uses: docker/metadata-action@v5
+        uses: docker/metadata-action@v6
         with:
           flavor: |
             latest=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
           images: |
             ghcr.io/groenator/iptvboss-docker-headless-beta
           tags: |
+            type=ref,event=branch
             type=ref,event=pr
+            type=ref,event=tag
             type=semver,pattern=v{{major}}.{{minor}}
             type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
             type=semver,pattern=v{{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
             type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
-            type=raw,value=${{ env.BETA_TAG }},enable=${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
+            type=raw,value=${{ env.BETA_TAG }},enable=${{ github.event_name == 'release' || startsWith(github.ref, 'refs/tags/') }}
 
       # Build and push Beta Image
       - name: Short commit
@@ -335,7 +343,7 @@ jobs:
         run: echo "{name}={value}::$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
 
       - name: Build and push final image
-        uses: docker/build-push-action@v5
+        uses: docker/build-push-action@v6
         with:
           platforms: linux/amd64,linux/arm64
           labels: ${{ steps.meta-beta.outputs.labels }}
